export const CATEGORY_ACTION_TYPES = {
    SET_CATEGORIES: "SET_CATEGORIES",
    FETCH_CATEGORIES_START: "category/FETCH_CATEGORIES_START",
    FETCH_CATEGORIES_SUCCES: "category/FETCH_CATEGORIES_SUCCES",
    FETCH_CATEGORIES_FAIL: "category/FETCH_CATEGORIES_FAIL"
} 
